#!/bin/bash
set -x

# Prepend time to output
export PS4=' $SECONDS + '

# Variables used in com directory organization
export NET=${NET:-aigfs}
export RUN=${RUN:-aigfs}

# Create temporary working directory
export DATAshared=${DATAROOT:?}/${RUN}_forecast_${cyc}_${aigfs_ver%.*}
export DATA=${DATAshared}/${jobid:?}
mkdir -p $DATA
cd $DATA

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ${DATA}/PDY
echo $PDY

export MAILTO=${MAILTO:-'nco.spa@noaa.gov'}

# Locations of outgoing data
export COMOUT=${COMOUT:-$(compath.py -o $NET/$aigfs_ver/$RUN.$PDY)}/${cyc}/model/atmos/grib2

# Create output directories
mkdir -p $COMOUT

# Execute ex-script
$HOMEaigfs/scripts/exaigfs_post.sh
export err=$?; err_chk

# Post successful completion message
msg="JOB $job HAS COMPLETED NORMALLY."
postmsg $jlogfile "$msg"

# Print exec output
if [ -e $pgmout ]; then
  cat $pgmout
fi

# Remove temporary working directory
if [ "${KEEPDATA^^}" != YES ]; then
  rm -rf $DATA
fi

date
