#!/bin/bash
set -x

# Prepend time to output
export PS4=' $SECONDS + '

# Create temporary working directory
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

# Create directories to store gfs inputs and final output
mkdir -p data output

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ${DATA}/PDY
echo $PDY

# Variables used in com directory organization
export NET=${NET:-aigfs}
export RUN=${RUN:-aigfs}

# loop over members and remove shared working directories
export DATAshared=${DATAROOT:?}/${RUN}_forecast_${cyc}_${aigfs_ver%.*}_${envir}
# if directory exists, remove it
[ -d "$DATAshared" ] && rm -rf "$DATAshared"

# Post successful completion message
msg="JOB $job HAS COMPLETED NORMALLY."
postmsg $jlogfile "$msg"

# Remove temporary working directory
if [ "${KEEPDATA^^}" != YES ]; then
  rm -rf $DATA
fi
